// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:flutter_dotenv/flutter_dotenv.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY'] ?? '',
    appId: '1:791506778320:web:7d1292d65cc799eeab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    authDomain: 'mis-jokes-project.firebaseapp.com',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY'] ?? '',
    appId: '1:791506778320:android:7e9afa74ea17fb6bab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY'] ?? '',
    appId: '1:791506778320:ios:626b86510fd53160ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2211080',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY'] ?? '',
    appId: '1:791506778320:ios:626b86510fd53160ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2211080',
  );

  static FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY'] ?? '',
    appId: '1:791506778320:web:1fd4efeb3e2de8d0ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    authDomain: 'mis-jokes-project.firebaseapp.com',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );
}
