// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDt6oT1pusOwIkcWRCV-oO-fBK20yy8eV0',
    appId: '1:791506778320:web:7d1292d65cc799eeab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    authDomain: 'mis-jokes-project.firebaseapp.com',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy5o0UfLEcg-mpP9C2Y6-oq_lPglMxSE4',
    appId: '1:791506778320:android:7e9afa74ea17fb6bab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNaBwEtjfERamA8ab5shvrt0C33ZgH330',
    appId: '1:791506778320:ios:626b86510fd53160ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2211080',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNaBwEtjfERamA8ab5shvrt0C33ZgH330',
    appId: '1:791506778320:ios:626b86510fd53160ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
    iosBundleId: 'com.example.lab2211080',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDt6oT1pusOwIkcWRCV-oO-fBK20yy8eV0',
    appId: '1:791506778320:web:1fd4efeb3e2de8d0ab46d5',
    messagingSenderId: '791506778320',
    projectId: 'mis-jokes-project',
    authDomain: 'mis-jokes-project.firebaseapp.com',
    storageBucket: 'mis-jokes-project.firebasestorage.app',
  );

}